FORMAT: 1A
HOST: http://www.google.com

# blog
Notes API is a *short texts saving* service similar to its physical paper presence on your table.

# Group Notes
Notes related resources of the **Notes API**

## Notes Collection [/posts]
### List all Posts [GET]
+ Response 200 (application/json)

        [{
          "id": 1, 
          "title"    : "Dancer.js, a high-level audio API",
          "author"  : "Oded Sagir",
          "thumbnail": "http://placehold.it/900x300&text=Post1",
            "tags"     : [ "web audio", "audio data", "webgl" ],
            "category" : "audio",
            "date"     : "7-30-2012",
            "preview"  : "dancer.js is a high-level audio API, usable with both Mozilla's Audio Data API and Webkit's Web Audio API with flash fallback, designed to make sweet visualizations.\nhttp://jsantell.github.com/dancer.js\n\n_v0.2.1 (6/15/2012)_\n\nFeatures\n\n---\n* Use real-time audio waveform and frequency data and map it to any arbitrary visualization\n* Leverage beat detection into your visualizations\n* Simple API to time callbacks and events to any section of a song\n* Supports Web Audio (webkit), Audio Data (mozilla) and flash fallback (v9+)\n* Extensible framework supporting plugins and custom behaviours",
            "content"  : null
        }, {
          "id": 2,
            "title"    : "Dust.js, a high-level templating API",
            "author"  : "Oded Sagir",
            "thumbnail": "http://placehold.it/900x300&text=Post2",
            "tags"     : [ "web", "templating" ],
            "category" : "templating",
            "date"     : "7-13-2012",
            "preview"  : "ffgfdkjsh  make sweet visualizations.\nhttp://jsantell.github.com/dancer.js\n\n_v0.2.1 (6/15/2012)_\n\nFeatures\n\n---\n* Use real-time audio waveform and frequency data and map it to any arbitrary visualization\n* Leverage beat detection into your visualizations\n* Simple API to time callbacks and events to any section of a song\n* Supports Web Audio (webkit), Audio Data (mozilla) and flash fallback (v9+)\n* Extensible framework supporting plugins and custom behaviours",
            "content"  : null
        }]

### Create a Post [POST]
+ Request (application/json)

        {
          "title"    : "New Post",
          "author"  : "Oded Sagir",
          "thumbnail": "http://placehold.it/900x300&text=Post3",
            "tags"     : [ "web audio", "audio data", "webgl" ],
            "category" : "audio",
            "date"     : "7-30-2012",
            "preview"  : "dancer.js is a high-level audio API, usable with both Mozilla's Audio Data API and Webkit's Web Audio API with flash fallback, designed to make sweet visualizations.\nhttp://jsantell.github.com/dancer.js\n\n_v0.2.1 (6/15/2012)_\n\nFeatures\n\n---\n* Use real-time audio waveform and frequency data and map it to any arbitrary visualization\n* Leverage beat detection into your visualizations\n* Simple API to time callbacks and events to any section of a song\n* Supports Web Audio (webkit), Audio Data (mozilla) and flash fallback (v9+)\n* Extensible framework supporting plugins and custom behaviours",
            "content"  : "some content"
        }

+ Response 201 (application/json)

        {
          "id": 3, 
          "title"    : "New Post",
          "author"  : "Oded Sagir",
          "thumbnail": "http://placehold.it/900x300&text=Post3",
            "tags"     : [ "web audio", "audio data", "webgl" ],
            "category" : "audio",
            "date"     : "7-30-2012",
            "preview"  : "dancer.js is a high-level audio API, usable with both Mozilla's Audio Data API and Webkit's Web Audio API with flash fallback, designed to make sweet visualizations.\nhttp://jsantell.github.com/dancer.js\n\n_v0.2.1 (6/15/2012)_\n\nFeatures\n\n---\n* Use real-time audio waveform and frequency data and map it to any arbitrary visualization\n* Leverage beat detection into your visualizations\n* Simple API to time callbacks and events to any section of a song\n* Supports Web Audio (webkit), Audio Data (mozilla) and flash fallback (v9+)\n* Extensible framework supporting plugins and custom behaviours",
            "content"  : "some content"
        }
        
## Note [/posts/{id}]
A single Note object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Note to perform action with. Has example value.

### Retrieve a Post [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": {id},
                "title"    : "Dancer.js, a high-level audio API",
                "tags"     : [ "web audio", "audio data", "webgl" ],
                "category" : "audio",
                "date"     : "7-30-2012",
                "preview"  : "dancer.js is a high-level audio API, usable with both Mozilla's Audio Data API and Webkit's Web Audio API with flash fallback, designed to make sweet visualizations.\nhttp://jsantell.github.com/dancer.js\n\n_v0.2.1 (6/15/2012)_\n\nFeatures\n\n---\n* Use real-time audio waveform and frequency data and map it to any arbitrary visualization\n* Leverage beat detection into your visualizations\n* Simple API to time callbacks and events to any section of a song\n* Supports Web Audio (webkit), Audio Data (mozilla) and flash fallback (v9+)\n* Extensible framework supporting plugins and custom behaviours",
                "content"  : "full post bla bla"
            }

### Remove a Post [DELETE]
+ Response 204
